### ISSUE TITLE
super mario odyssey 64 port

### ISSUE THREAD

**Issue by no-hanzos** [aspieweeb759/3ds-SM64-romhack-port-patches#1]
i would really like to see you compile a 3ds version of kaze's super mario odyssey 64 romhack. https://www.youtube.com/watch?v=pAFxi6nuD80
since i dont have access to a windows 10 machine i cant follow the instructions from tutorials provided in the repo and as such cannot do it myself

**Comment by aspieweeb759** [comment]
Kaze's romhacks arent able to be ported to ex-alo, his code is oftentimes very broken

**Comment by no-hanzos** [comment]
i see thanks for explaining
